#ifndef DEMO_TC334_BOARD_HPP
#define DEMO_TC334_BOARD_HPP

extern "C"
{
#include "IfxAsclin_Asc.h"
}

#define BOARD_ASCLIN0_SERIAL_PIN_RX IfxAsclin0_RXA_P14_1_IN
#define BOARD_ASCLIN0_SERIAL_PIN_TX IfxAsclin0_TX_P14_0_OUT
#define BOARD_ASCLIN0_TX_BUFFER_SIZE 128
#define BOARD_ASCLIN0_BAUDRATE 115200

#define BOARD_ISR_PRIORITY_ASCLIN0_TX 19
#define BOARD_ISR_PRIORITY_GPT12_TIMER_TASK_1KHz 6
#define BOARD_ISR_PRIORITY_GPT12_TIMER_TASK_10KHz 7 // Highest number = hughest priority
#define BOARD_ISR_PROVIDER_GPT12_TIMER IfxSrc_Tos_cpu0

#define BOARD_LED1_MODULE MODULE_P00
#define BOARD_LED1_PIN 5
#define BOARD_LED2_MODULE MODULE_P00
#define BOARD_LED2_PIN 6
#define BOARD_X2_3_MODULE MODULE_P00
#define BOARD_X2_3_PIN 0
#define BOARD_X2_5_MODULE MODULE_P00
#define BOARD_X2_5_PIN 2

#define BOARD_TASK_LOWFREQ_IO_MODULE BOARD_X2_3_MODULE
#define BOARD_TASK_LOWFREQ_IO_PIN BOARD_X2_3_PIN

#define BOARD_TASK_HIGHFREQ_IO_MODULE BOARD_X2_5_MODULE
#define BOARD_TASK_HIGHFREQ_IO_PIN BOARD_X2_5_PIN

extern IfxAsclin_Asc g_asclin0;

void init_board();

void set_led1(bool val);
void set_led2(bool val);

#endif // DEMO_TC334_BOARD_HPP